// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type ApiKey struct {
	ProjectID    string
	HashedSecret []byte
}

type Currency struct {
	Code string
}

type ExchangeRate struct {
	FromCurrency string
	ToCurrency   string
	Rate         float32
	RateAt       time.Time
}
